"""
Django settings for mysite project.

Generated by 'django-admin startproject' using Django 2.0.

For more information on this file, see
https://docs.djangoproject.com/en/2.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.0/ref/settings/
"""
import os
from.base import *

SECRET_KEY = 'o6gf^8$mnfxy51y(sx_$ar9r!f4^=1zgk!gl=)jp%45dbv!c#k'
# SECURITY WARNIN G: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'mysite_db',
        'USER':'root',
        'PASSWORD':'mlz19680307',
        'HOST':'127.0.0.1',
        'PORT':'3306',
    }
}


